version: '3.8'
services:
  ## Cortex
  elasticsearch:
    image: 'elasticsearch:7.9.3'
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - './vol/elasticsearch/data:/usr/share/elasticsearch/data'
      - './vol/elasticsearch/logs:/usr/share/elasticsearch/logs'
  cortex:
    image: 'thehiveproject/cortex:latest'
    container_name: cortex
    restart: unless-stopped
    command:
      --job-directory ${JOB_DIRECTORY}
    environment:
      - 'JOB_DIRECTORY=${JOB_DIRECTORY}'
    volumes:
      - './vol/cortex/application.conf:/etc/cortex/application.conf'
      - '${JOB_DIRECTORY}:${JOB_DIRECTORY}'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'

  ## TheHive
  thehive:
    image: 'thehiveproject/thehive4:latest'
    container_name: 'thehive4'
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - './vol/thehive/application.conf:/etc/thehive/application.conf'
      - './vol/thehive/berkley:/opt/berkley'
      - './vol/thehive/data:/opt/data'
    networks:
      - default
    command: '--no-config --no-config-secret'

  ## NodeRED
  node-red:
    image: nodered/node-red:latest
    container_name: 'node-red'
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./vol/node-red/data:/data
    networks:
      - nodered-net
      - default

networks:
  nodered-net: null
  default: null
